spring.application.name=fake-image-detector
server.port=8081


# Your Hugging Face Token 
huggingface.api.key=Bearer ${HF_API_TOKEN}
huggingface.api.url=https://router.huggingface.co/hf-inference/models/umm-maybe/AI-image-detector

# Allow files up to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

