spring.application.name=fake-image-detector

# Your Hugging Face Token 
huggingface.api.key=Bearer ${HF_API_TOKEN}
huggingface.api.url=https://api-inference.huggingface.co/models/umm-maybe/AI-image-detector

# Allow files up to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

